Implement UPDATE_CLIENT_SIDE_UI signal
fcitx/fcitx5-gtk pull request #3
Opened 2020-08-17 12:36 UTC by nntae

2020-08-17 18:00 UTC, wengxt requested changes

2020-08-17 18:00 UTC, wengxt commented on fcitx-gclient/fcitxgclient.c
> +        GPtrArray *preedit_strings = g_ptr_array_new_with_free_func(_item_free),
nit: prefer multiple declaration.

2020-08-17 18:00 UTC, wengxt commented on fcitx-gclient/fcitxgclient.c
> +        // Populate the (ss) candidate GPtrArray
nit: create a function like buildFormattedTextArray for readability.

2020-08-17 18:00 UTC, wengxt commented on fcitx-gclient/fcitxgclient.c
> +        item->string = g_strdup(string);
Looks like we can take the ownership of string here instead of g_strdup to avoid one allocation.
Same for the candidate part.

2020-08-19 16:32 UTC, nntae reviewed
Pushed the requested changes

2020-08-19 18:00 UTC, wengxt approved these changes

2020-08-19 18:01 UTC, merged